Repository Merce213/3WA-Yams-Game, pull requests merged in 2024-05, with the labels that each got.

#3 [YAMS-019] add basic functions to handle the game logic
  yams-front/src/config/combinaisons.js
  yams-front/src/services/game.js
Labels: enhancement

#4 [YAMS-006] Login page for the back office admin
  yams-front/src/App.jsx
  yams-front/src/pages/Login.jsx
Labels: enhancement

#5 [YAMS-014] Implement API endpoints for the front
  yams-front/src/App.jsx
  yams-front/src/config/api.js
  yams-front/src/features/auth/index.jsx
  yams-front/src/features/crud/index.jsx
  yams-front/src/features/pastries/index.jsx
  yams-front/src/features/user/index.jsx
  yams-front/src/store/index.js
Labels: enhancement

#6 [YAMS-020] Game Over page + responsive, added img skull and new font
  yams-front/src/App.jsx
  yams-front/src/assets/skull.png
  yams-front/src/components/NavBar.jsx
  yams-front/src/index.css
  yams-front/src/pages/GameOver.jsx
  yams-front/tailwind.config.js
Labels: enhancement

#7 [YAMS-005] Win page + responsive
  yams-front/src/App.jsx
  yams-front/src/assets/star.png
  yams-front/src/assets/trophy.png
  yams-front/src/components/Button.jsx
  yams-front/src/pages/GameOver.jsx
  yams-front/src/pages/Win.jsx
  yams-front/tailwind.config.js
Labels: enhancement

#8 [YAMS-010] handle the connection of the user and add a modal component
  yams-front/package-lock.json
  yams-front/package.json
  yams-front/src/components/StatusMessageModal.jsx
  yams-front/src/pages/Login.jsx
  yams-front/tailwind.config.js
Labels: enhancement

#9 [YAMS-004] Game page
  yams-front/src/App.jsx
  yams-front/src/assets/die1.png
  yams-front/src/assets/die2.png
  yams-front/src/assets/die3.png
  yams-front/src/assets/die4.png
  yams-front/src/assets/die5.png
  yams-front/src/assets/die6.png
  yams-front/src/pages/Game.jsx
  yams-front/tailwind.config.js
Labels: enhancement

#10 [YAMS-007] Back Office Page
  yams-front/package-lock.json
  yams-front/package.json
  yams-front/src/App.jsx
  yams-front/src/components/LayoutNav.jsx
  yams-front/src/components/NavbarAdmin.jsx
  yams-front/src/components/Sidebar.jsx
  yams-front/src/pages/Dashboard.jsx
  yams-front/tailwind.config.js
Labels: enhancement

#11 [YAMS-009] add the main logic for the game + animations
  yams-api/src/Data/pastries.json
  yams-api/src/routes/game.ts
  yams-front/src/assets/index.js
  yams-front/src/assets/startMessage.png
  yams-front/src/components/Die.jsx
  yams-front/src/components/PreloadImages.jsx
  yams-front/src/components/Reward.jsx
  yams-front/src/components/RewardsList.jsx
  yams-front/src/config/combinaisons.js
  yams-front/src/config/settings.js
  yams-front/src/features/auth/index.jsx
  yams-front/src/index.css
  yams-front/src/main.jsx
  yams-front/src/pages/Game.jsx
  yams-front/src/pages/Home.jsx
  yams-front/src/pages/Win.jsx
  yams-front/src/services/game.js
  yams-front/tailwind.config.js
Labels: enhancement

#13 [YAMS-022] fetch all pastries and display them
  yams-front/src/components/ModalAddPastry.jsx
  yams-front/src/components/ModalEditPastry.jsx
  yams-front/src/components/PastriesList.jsx
  yams-front/src/components/PastriesTable.jsx
  yams-front/src/features/crud/index.jsx
  yams-front/src/pages/AdminPastries.jsx
Labels: enhancement

#14 [YAMS-023] handle the authentification and protect the back office routes
  yams-front/src/App.jsx
  yams-front/src/components/LayoutNav.jsx
  yams-front/src/components/Sidebar.jsx
  yams-front/src/features/user/index.jsx
  yams-front/src/pages/Login.jsx
  yams-front/src/utils/ProtectedRoutes.jsx
Labels: enhancement

#15 [YAMS-021] allow the admin to logout + bug correction
  yams-front/src/components/NavbarAdmin.jsx
  yams-front/src/components/StatusMessageModal.jsx
  yams-front/src/components/admin/UserMenu.jsx
  yams-front/src/utils/ProtectedRoutes.jsx
Labels: enhancement

#16 [YAMS-012] Edit a pastry
  yams-front/src/components/ModalAddPastry.jsx
  yams-front/src/components/ModalEditPastry.jsx
  yams-front/src/features/crud/index.jsx
Labels: enhancement

#17 [YAMS-024] Add credits page + minor adjustement to style + lower delay before displaying rewards
  yams-front/src/App.jsx
  yams-front/src/components/NavBar.jsx
  yams-front/src/components/RewardsList.jsx
  yams-front/src/pages/Credits.jsx
  yams-front/src/pages/Home.jsx
Labels: enhancement

#18 [YAMS-011] Add readme
  yams-front/README.md
  yams-front/src/pages/Game.jsx
Labels: documentation

#19 [YAMS-025] Add a new pastry
  yams-api/src/routes/pastry.ts
  yams-front/src/components/ModalAddPastry.jsx
  yams-front/src/features/crud/index.jsx
Labels: enhancement

#21 [YAMS-027] Delete a pastry
  yams-front/src/components/ModalDeletePastry.jsx
  yams-front/src/features/crud/index.jsx
Labels: enhancement

#20 [YAMS-011] Add readme
  README.md
  yams-front/src/pages/Game.jsx
Labels: documentation, enhancement

#23 [YAMS-028] Add missing credits
  yams-front/src/pages/Credits.jsx
Labels: enhancement
